%get core cells

%below is the code to input into menu selector, option 8
% %         inputFile = 'raw_expression_matrix.csv';
% %         coreCells = 'core_cells.csv';
% %         clusterFile = 'clusters.csv';
% %         loadTranscriptomicsData2(inputFile, coreCells, clusterFile);
%      
%         rawFileName = 'core_matrix.csv';
%         randFileName = shuffle_raw_updated(rawFileName, '');
%         rawDifferences = raw_MouseLight(rawFileName);
%         randDifferences = raw_MouseLight(randFileName);
%         [p, stats] = create_scaled_histogram(rawDifferences, randDifferences, '');

function loadTranscriptomicsData2(inputFile, coreCellFile, clusterFile)
    data = readmatrix(inputFile);
    data = data.';
    
    coreCells = table2cell(readtable(coreCellFile));
    [nRows, nCols] = size(data);
    
    clusters = table2cell(readtable(clusterFile));   
    clusters(:, 1) = [];
    newClusters = clusters;
    
    toDelete = {};
    toDeleteIdx = 1;
    
    for i = 1:nRows
        if cell2mat(coreCells(i)) ~= 0
           toDelete{toDeleteIdx} = i;
           toDeleteIdx = toDeleteIdx+1;
        end
    end 
    
    toDelete = cell2mat(toDelete);
    data(toDelete, :) = [];
    newClusters(toDelete, :) = [];
    %writematrix(data, 'core_cell_expression.csv');
    %writecell(newClusters, 'core_clusters.csv');
    [nRows, nCols] = size(data);
    
   % coi = {'GABA_Vip-Vip_Mybpc1' 'Gluta_L4-L4_Ctxn3' 'GABA_Pvalb-Pvalb_Gpx3'}; % clusters of interest
   
   coi = {'GABA_Vip-Vip_Mybpc1'...
    'GABA_Vip-Vip_Parm1'...
    'Gluta_L4-L4_Ctxn3'...
    'GABA_Vip-Vip_Chat'...
    'Gluta_L2_3-L2_3_Ptgs2'...
    'Gluta_L2-L2_Ngb'...
    'GABA_Pvalb-Pvalb_Gpx3'...
    'GABA_Vip-Vip_Gpc3'...
    'GABA_Vip-Vip_Sncg'...
    'Gluta_L4-L4_Scnn1a'...
    'NonNeu_Astro-Astro_Aqp4'...
    'GABA_Ndnf-Ndnf_Cxcl14'...
    'Gluta_L5a-L5a_Hsd11b1'...
    'Gluta_L4-L4_Arf5'...
    'Gluta_L5a-L5a_Batf3'...
    'Gluta_L5-L5_Ucma'...
    'Gluta_L5a-L5a_Tcerg1l'...
    'NonNeu_Micro-Micro_Ctss'...
    'GABA_Pvalb-Pvalb_Tacr3'...
    'NonNeu_Endo-Endo_Xdh'...
    'GABA_Sst-Sst_Cbln4'...
    'GABA_Ndnf-Ndnf_Car4'...
    'NonNeu_SMC-SMC_Myl9'...
    'Gluta_L6b-L6b_Serpinb11'...
    'Gluta_L6b-L6b_Rgs12'...
    'GABA_Sncg-Sncg'...
    'GABA_Igtp-Igtp'...
    'GABA_Pvalb-Pvalb_Cpne5'...
    'GABA_Pvalb-Pvalb_Rspo2'...
    'NonNeu_Oligo-Oligo_96*Rik'...
    'GABA_Smad3-Smad3'...
    'GABA_Pvalb-Pvalb_Wt1'...
    'NonNeu_Oligo-Oligo_Opalin'...
    'GABA_Pvalb-Pvalb_Tpbg'...
    'GABA_Sst-Sst_Myh8'...
    'NonNeu_OPC-OPC_Pdgfra'...
    'GABA_Pvalb-Pvalb_Obox3'...
    'Gluta_L5b-L5b_Tph2'...
    'GABA_Sst-Sst_Tacstd2'...
    'GABA_Sst-Sst_Th'...
    'Gluta_L6a-L6a_Sla'...
    'GABA_Sst-Sst_Chodl'...
    'GABA_Sst-Sst_Cdk6'...
    'Gluta_L5a-L5a_Pde1c'...
    'Gluta_L6a-L6a_Mgp'...
    'Gluta_L6a-L6a_Syt17'...
    'Gluta_L5b-L5b_Chrna6'...
    'Gluta_L5b-L5b_Cdh13'...
    'Gluta_L6a-L6a_Car12'};
   
    newData = data;
    members = ismember(newClusters, coi);
    toDelete = {};
    toDeleteIdx = 1;
    
    for i = 1:nRows
        if members(i) == 0
           toDelete{toDeleteIdx} = i;
           toDeleteIdx = toDeleteIdx+1;
        end
    end 
    
    toDelete = cell2mat(toDelete);
    newData(toDelete, :) = [];
    %newData( :, all( ~any( newData ), 1 ) ) = [];
    %newData = newData*100;
    %writematrix(newData, 'core_matrix.csv');
    
    %[coeff,score,latent,tsquared,explained,mu] = pca(newData);
    %idx = find(cumsum(explained)>99,1);
    %scoreTrain95 = score(:,1:idx);
    
    %newScore = round(scoreTrain95);
    %newScore = abs(newScore);
    
    [coeff, score, latent] = pca(newData, 'NumComponents', 3);
    writematrix(newScore, 'core_matrix_pca.csv');  
    
end
         
% end